config/routes.rb
Huntapp::Application.routes.draw do
  resources :static_pages

  
  resources :maps do
    resources :waypoints, :only => [:new, :create]
    resources :hunts, :only => [:new, :index, :create]
  end
  
  resources :hunts, :only => [:show, :update, :destroy] do
    member do
      post 'sync'
    end
  end
  
  resources :positions, :only => [:show]
  
  resources :users, :only => [:new, :create]
  match "signup" => 'users#new', :as => :signup
  
  resource :user_sessions, :only => [:new, :create, :destroy]
  match "signin" => 'user_sessions#new', :as => :signin, :method => :get
  match "signout" => 'user_sessions#destroy', :as => :signout, :method => :destroy
  
  match "activity" => 'activity#index', :as => :activity
  match "live-hunts" => 'activity#public', :as => :live_hunts
  match "start-mapping" => 'maps#new'
  resources :waypoints, :except => [:new, :create]
  
  root :to => 'pages#home'
  

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # GET /static_pages
  # GET /static_pages.xml
  def index
    @static_pages = StaticPage.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @static_pages }
    end
  end

  # GET /static_pages/1
  # GET /static_pages/1.xml
  def show
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @static_page }
    end
  end

  # GET /static_pages/new
  # GET /static_pages/new.xml
  def new
    @static_page = StaticPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @static_page }
    end
  end

  # GET /static_pages/1/edit
  def edit
    @static_page = StaticPage.find(params[:id])
  end

  # POST /static_pages
  # POST /static_pages.xml
  def create
    @static_page = StaticPage.new(params[:static_page])

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to(@static_page, :notice => 'Static page was successfully created.') }
        format.xml  { render :xml => @static_page, :status => :created, :location => @static_page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @static_page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /static_pages/1
  # PUT /static_pages/1.xml
  def update
    @static_page = StaticPage.find(params[:id])

    respond_to do |format|
      if @static_page.update_attributes(params[:static_page])
        format.html { redirect_to(@static_page, :notice => 'Static page was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @static_page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.xml
  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to(static_pages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<div class="field">
    <%= f.label :url_alias %> (Example: static-page-name)<br />
    <%= f.text_field :url_alias %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<h1>Listing static_pages</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Url Alias</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @static_pages.each do |static_page| %>
  <tr>
    <td><%= static_page.name %></td>
	<td><%= static_page.url_alias %></td>	
    <td><%= static_page.body %></td>
    <td><%= link_to 'Show', static_page %></td>
    <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
    <td><%= link_to 'Destroy', static_page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @static_page.name %>
</p>

<p>
  <b>Body:</b>
  <%= @static_page.body %>
</p>


<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>