config/routes.rb
Huntapp::Application.routes.draw do
  resources :static_pages

  
  resources :maps do
    resources :waypoints, :only => [:new, :create]
    resources :hunts, :only => [:new, :index, :create]
  end
  
  resources :hunts, :only => [:show, :update, :destroy] do
    member do
      post 'sync'
    end
  end
  
  resources :positions, :only => [:show]
  
  resources :users, :only => [:new, :create]
  match "signup" => 'users#new', :as => :signup
  
  resource :user_sessions, :only => [:new, :create, :destroy]
  match "signin" => 'user_sessions#new', :as => :signin, :method => :get
  match "signout" => 'user_sessions#destroy', :as => :signout, :method => :destroy
  
  match "activity" => 'activity#index', :as => :activity
  match "live-hunts" => 'activity#public', :as => :live_hunts
  match "start-mapping" => 'maps#new'
  resources :waypoints, :except => [:new, :create]
  
  root :to => 'pages#home'
  

end

app/models/map.rb
require 'military_alphabet'
# The core model of the app. It has a general location and has waypoints which show
# a hunt's route
class Map < ActiveRecord::Base
  
  has_many :waypoints, :order => :position
  has_many :hunts
  
  before_validation :auto_generate_name, :on => :create, :unless => :named?
  
    def total_distance
      Waypoint.select("sum(distance) as total_distance").where({:map_id => self.id}).first.total_distance
    end
    
    def thumbnail_image_url(options = {})
      options.reverse_merge!(
        :size => [50,50]
      )
      options[:size] = [options[:size], options[:size]] unless options[:size].kind_of?(Array)
      size = "#{options[:size].first}x#{options[:size].last}"
      location = "#{start_location.lat},#{start_location.lng}" if self.start_location.present?
      "http://maps.google.com/maps/api/staticmap?center=#{location}&zoom=12&size=#{size}&maptype=terrain&sensor=false"
    end
    
    def start_location
      self.waypoints.first
    end
    
    def named?
      self.name.present?
    end
  
  protected
  
    def auto_generate_name
      alphabet = MilitaryAlphabet.new
      character = alphabet[count]
      self.name = "Map #{character}"
      
    end
    
    def count
      Map.count
    end
      
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  
  respond_to :html, :json
  before_filter :require_user, :only => [:index]
  before_filter :find_maps, :only => :index

  # a list of your hunts
  def index
    @maps = current_user.owned_maps
    respond_with @maps, :include => :waypoints
  end
  
  # we're going to autosave new hunts and redirect
  # breaking REST contract here
  def new
      
    if current_user
      @map = Map.create
      current_user.memberships.create(:map => @map, :level => 'owner')
    else
      self.unsaved_map = Map.create unless unsaved_map
      @map = unsaved_map
    end
    redirect_to [:edit, @map]
  end
  
  def create
    @map = Map.new(params[:map])
    if current_user
      current_user.memberships.create(:map => @map, :level => 'owner') unless current_user.owned_maps.include?(@map)
    else
      unsaved_map = @map
    end
    if @map.save
      respond_with @map, :include => :waypoints
    else
      respond_with @map.errors
    end
  end
  
  # overview of the hunt
  # overlay the last hunt activity
  # show a list of sessions to display
  # show the notes on the map
  def show
    find_map
    respond_to do |format|
      format.html do
        redirect_to edit_map_path(@map)
      end
      format.any(:json, :xml) do
        respond_with @map, :include => :waypoints
      end
    end

  end
    
  # edit the hunt details/waypoints
  # the show and edit views will pretty much be the same action
  # since most editing will be javascript heavy using the Google Maps API
  def edit
    find_map
    respond_with @map, :include => :waypoints
  end
  
  
  def destroy
    find_map
    @map.destroy
    respond_with @map
  end
  
  
  protected
    
    
    def find_maps
      if current_user
        @maps = current_user.maps
      else
        @maps = [unsaved_map].compact
      end
    end
    
    def find_map
      if current_user
        @map = current_user.owned_maps.find(params[:id])
      else
        @map = unsaved_map
      end
    end
    
end

app/helpers/maps_helper.rb
module MapsHelper
  
  def distance_in_meters(distance)
    number_with_delimiter(number_with_precision(distance, :precision => 1)) + " meters" if distance
  end
  
  
  def human_distance(distance)
    # distance is in meters, so convert first o feet
    return unless distance
    miles = distance.to_f / 1609.344
    number_with_delimiter(number_with_precision(miles, :precision => 1)) + " miles" if distance
    
  end
  
  def heading(h)
    number_with_precision(h, :precision => 0) + "&deg;".html_safe if h
  end
  
  def heading_name(h)
    return unless h.present?
    h = h + 360 if h < -23
    i = h.to_i
    label = {
      (-23..23) => 'N',
      (23..68) => 'NE',
      (68..113) => 'E',
      (113..157) => 'SE',
      (157..203) => 'S',
      (203..248) => 'SW',
      (248..293) => 'W',
      (293..338) => 'NW',
      (338..360) => 'N'
    }.detect { |pair| pair.first.cover?(i) }
    label ? label.last : '?'
  end
  
end

app/views/maps/edit.html.erb
<div id="location">
  <%= link_to '<< Maps', maps_path %>
</div>
<%- unless current_user? -%>
<div id="login-notice">
  <%= link_to 'Sign Up', signup_path %> or <%= link_to 'Log In', signin_path %> to save this map!
</div>
<%- end -%>
<div id="hunt_toolbar">
  <div class="location-search-field-container"><input type="text" id="location-search-field"> <button id="location-search-submit">Search</button></div>
  <div class="toolbar-button map-destroy">
    <%= link_to 'Delete Map', @map, :method => :delete, :confirm => 'Are you sure?' %>
  </div>
</div>
<div id="hunt_map">
</div>

<script type="text/javascript" charset="utf-8">
  // by default let's center on the US
  var map = new google.maps.Map($('hunt_map'), {
    center: new google.maps.LatLng(37.23,-95.67),
    zoom:4,
    mapTypeId: google.maps.MapTypeId.TERRAIN,
    streetViewControl: false
  });
  
  var hunt_map = new Map(<%= @map.id %>, { map:map, waypoint_list: $('waypoint_list') });
  
  var current_waypoint;
  
  
  // $('new_waypoint').observe('click', function(e){
  //   e.preventDefault();
  //   if(!map.editing) map.startAddWayPoint();
  // });
  // 
  document.observe('keydown', function(e){
    if(e.which == 82){
      hunt_map.fitMap();
    }
  })
  
  
  var geocoder = new google.maps.Geocoder();
  var field = $('location-search-field');
  var button = $('location-search-submit');
  var search_function = function(){
    console.log("We whould search", field.getValue());
    var address = field.getValue();
    geocoder.geocode({'address' : address, 'region' : 'US'}, function(results, status){
      console.log(results, status);
      if (status == google.maps.GeocoderStatus.OK) {
        // map.setCenter(results[0].geometry.location);
        map.fitBounds(results[0].geometry.bounds);
      };
    });
  }
  
  
  
  $('location-search-submit').observe('click', search_function);
  $('location-search-field').observe('keypress', function(e){
    if (e.which == Event.KEY_RETURN) {
      search_function();
    };
  });
  
  
</script>

app/views/maps/index.html.erb
<h2>Hunts</h2>
<%= link_to 'Create new Map', :new_map %>
<%- if @maps.count > 0 -%>
<ul>
  <%- @maps.each do |map| -%>
  <li><%= link_to map.name, map %></li>
  <%- end -%>
</ul>
<%- end -%>

app/views/maps/show.html.erb
<div id="location">
  <%= link_to '<< Maps', maps_path %>
</div>
<%- unless current_user? -%>
<div id="login-notice">
  <%= link_to 'Sign Up', signup_path %> or <%= link_to 'Log In', signin_path %> to save this map!
</div>
<%- end -%>
<div id="hunt_toolbar">
  <div class="location-search-field-container"><input type="text" id="location-search-field"> <button id="location-search-submit">Search</button></div>
</div>
<div id="hunt_map">
</div>

<script type="text/javascript" charset="utf-8">
  // by default let's center on the US
  var map = new google.maps.Map($('hunt_map'), {
    center: new google.maps.LatLng(37.23,-95.67),
    zoom:4,
    mapTypeId: google.maps.MapTypeId.TERRAIN,
    streetViewControl: false
  });
  
  var hunt_map = new Map(<%= @map.id %>, { map:map, waypoint_list: $('waypoint_list') });
  
  var current_waypoint;
  
  
  // $('new_waypoint').observe('click', function(e){
  //   e.preventDefault();
  //   if(!map.editing) map.startAddWayPoint();
  // });
  // 
  document.observe('keydown', function(e){
    if(e.which == 82){
      hunt_map.fitMap();
    }
  })
  
  
  var geocoder = new google.maps.Geocoder();
  var field = $('location-search-field');
  var button = $('location-search-submit');
  var search_function = function(){
    console.log("We whould search", field.getValue());
    var address = field.getValue();
    geocoder.geocode({'address' : address, 'region' : 'US'}, function(results, status){
      console.log(results, status);
      if (status == google.maps.GeocoderStatus.OK) {
        // map.setCenter(results[0].geometry.location);
        map.fitBounds(results[0].geometry.bounds);
      };
    });
  }
  
  
  
  $('location-search-submit').observe('click', search_function);
  $('location-search-field').observe('keypress', function(e){
    if (e.which == Event.KEY_RETURN) {
      search_function();
    };
  });
  
  
</script>