config/routes.rb
Huntapp::Application.routes.draw do
  resources :static_pages

  
  resources :maps do
    resources :waypoints, :only => [:new, :create]
    resources :hunts, :only => [:new, :index, :create]
  end
  
  resources :hunts, :only => [:show, :update, :destroy] do
    member do
      post 'sync'
    end
  end
  
  resources :positions, :only => [:show]
  
  resources :users, :only => [:new, :create]
  match "signup" => 'users#new', :as => :signup
  
  resource :user_sessions, :only => [:new, :create, :destroy]
  match "signin" => 'user_sessions#new', :as => :signin, :method => :get
  match "signout" => 'user_sessions#destroy', :as => :signout, :method => :destroy
  
  match "activity" => 'activity#index', :as => :activity
  match "live-hunts" => 'activity#public', :as => :live_hunts
  match "start-mapping" => 'maps#new'
  resources :waypoints, :except => [:new, :create]
  
  root :to => 'pages#home'
  

end

app/models/hunt.rb
# Represents the actual activity of a user going out and hunting. This tracks an individuals activity for
# a specific hunt. Should we require a user to be within a certain distance of the first waypoint to start?
# 
# the client should be able to queue up all activity locally without interacting with a server
class Hunt < ActiveRecord::Base
  
  attr_protected :created_at, :udpated_at
  
  belongs_to :map
  belongs_to :user
  
  scope :recent, order('last_recorded_at DESC, finished_at DESC, started_at DESC').where(["positions_count > 0"])
  scope :active, lambda {
    where({:finished_at => nil}).where(["last_recorded_at > ?", 1.day.ago])
  }
  scope :finished, lambda {
    where(["finished_at < ? OR last_recorded_at < ?", Time.now, 1.day.ago])
  } 
  
  # the path/route this session took
  has_many :positions, :order => :recorded_at, :after_add => :update_recorded_at
  
  # the notes/photos/videos made along the way
  has_many :notes, :order => :created_at
  
  def add_positions(location_data)
    location_data.collect { |location|
      self.positions.create(location)
    }
  end
  
  def started_at_ms=ms
    self.started_at = Time.at(ms.to_i/1000)
  end
  
  def started_at_ms
    self.started_at.to_i * 1000 if self.started_at?
  end


  def finished_at_ms=ms
    self.finished_at = Time.at(ms.to_i/1000)
  end
  
  def finished_at_ms
    self.finished_at.to_i * 1000 if self.finished_at?
  end
  
  def map_progress_url(options={})
    options.reverse_merge! :width => 480, :height => 320
    gmap = GoogleStaticMap.new(:width => options[:width], :height => options[:height])
    
    # add the markers for the map
    # map_path = MapPath.new(:weight => 3, :color => "0x00000099")
    current_location = positions.reorder('recorded_at DESC').first
    gmap.markers << MapMarker.new(:color => 'orange', :location => MapLocation.new(:latitude => current_location.lat , :longitude => current_location.lng )) if current_location.present?
    # self.map.waypoints.each do |waypoint|
    #   location = MapLocation.new(:latitude => waypoint.lat, :longitude => waypoint.lng)
    #   gmap.markers << MapMarker.new(
    #     :icon => 'http://mmh.heroku.com/images/waypoint-marker.png',
    #     :shadow => false,
    #     :location => location,
    #   )
    #   map_path.points << location
    # end
    # gmap.paths << map_path
    # logger.debug "URL: #{gmap.url}"
    gmap.url
  end
  
  protected
    
    def update_recorded_at(position)
      if self.last_recorded_at.nil? || self.last_recorded_at < position.recorded_at
        self.last_recorded_at = position.recorded_at
        self.save(false)
      end
    end
  
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController
  respond_to :html, :json
  
  # Find the hunt to display
  # Pull up the map it belongs to
  # Render the hunt and the map together
  def show
    @hunt = Hunt.find(params[:id])
    @map = @hunt.map
    respond_with @hunt, :include => :positions
  end
  
  def create
    # find the hunt that this hunt is for
    @map = current_user.owned_maps.find(params[:map_id])
    @hunt = @map.hunts.build(:user => current_user)
    @hunt.attributes = params[:hunt]
    if @hunt.save
      respond_with @hunt, :include => :positions
    else
      respond_with @hunt.errors      
    end
    
  end
  
  def update
    @hunt = current_user.hunts.find(params[:id])
    @hunt.attributes = params[:hunt]
    if @hunt.save
      respond_with @hunt
    else
      respond_with @hunt.errors
    end
  end
  
  # post progress to a hunt
  # look up the hunt
  def sync
    @hunt = current_user.hunts.find(params[:id])
    @positions = @hunt.add_positions params[:positions]
    
    # TODO: we need a way of getting note attachment data through JSON
    # @notes = @hunt.add_notes params[:notes]
    # attach the notes and locations to the hunt
    
    # return a hash of the locations and notes in the same order that they were sent
    logger.debug "We have positions right? #{@positions}"
    respond_to do |format|
      format.json { render :json => { 'positions' => @positions } }
    end
    
  end
  
end

app/helpers/hunts_helper.rb
module HuntsHelper
end

app/views/hunts/edit.html.erb
<div id="location">
  <%= link_to '<< Hunts', hunts_path %>
</div>
<%- unless current_user? -%>
<div id="login-notice">
  <%= link_to 'Sign Up', signup_path %> or <%= link_to 'Log In', signin_path %> to save this hunt!
</div>
<%- end -%>
<div id="hunt_sidebar">
  <div class="panel">
    <h2><%= @hunt.name %></h2>
    <div class="hunt_meta">
      Total Distance: <span class="hunt_distance"><%= distance_in_meters @hunt.total_distance %></span>
    </div>
  </div>
  <div class="panel">
    <h3>Waypoints</h3>
    <%= link_to '+', [:new, @hunt, :waypoint], :title => 'Add Waypoint', :id => 'new_waypoint' %>
    <div id="waypoint_list">
    <%- @hunt.waypoints.each do |waypoint| -%>
    <div class="waypoint" id="waypoint_<%= waypoint.id %>">
      <div class="name"><%= waypoint.name %></div>
      <div class="next_waypoint">
      <%- if @hunt.waypoints.last != waypoint -%>
        Next
        <span class="distance"><%= distance_in_meters waypoint.distance %></span> at
        <span class="heading"><%= heading waypoint.heading %> <%= heading_name waypoint.heading %></span>
      <%- else -%>
        Final Waypoint
      <%- end -%>
      </div>
      <div class="waypoint_options">
        <%= link_to 'Rename', waypoint_path(waypoint), :class => 'rename' %>
      </div>
    </div>
    <%- end -%>
    </div>
  </div>
</div>

<div id="hunt_map">
</div>

<script type="text/javascript" charset="utf-8">
  // by default let's center on the US
  var map = new google.maps.Map($('hunt_map'), {
    center: new google.maps.LatLng(37.23,-95.67),
    zoom:4,
    mapTypeId: google.maps.MapTypeId.TERRAIN
  });
  
  var hunt = new Hunt(<%= @hunt.id %>, { map:map, waypoint_list: $('waypoint_list') });
  
  var current_waypoint;
  
  $('new_waypoint').observe('click', function(e){
    e.preventDefault();
    if(!hunt.editing) hunt.startAddWayPoint();
  });
  
  document.observe('keydown', function(e){
    if(hunt.ignore_shortcuts) return;
    if (e.which == 65 && !hunt.editing) {
      e.preventDefault();
      hunt.startAddWayPoint();
      hunt.closeWindow();
    }else if(e.which == 27) {
      if(hunt.editing) hunt.endAddWayPoint();
      hunt.closeWindow();
    }else if(e.which == 82){
      hunt.fitMap();
    }
  })
  
  
</script>

app/views/hunts/show.html.haml
.sidebar.col4
  %h2 Hunt Details
  %p
    %strong Started
    = time_ago_in_words(@hunt.started_at || @hunt.created_at)
    ago
  - if @hunt.finished_at?
    %p
      %strong Finished
      = time_ago_in_words(@hunt.finished_at)
      ago
  %p
    %strong Last Update
    - if @hunt.positions.last.present?
      = time_ago_in_words @hunt.positions.last.recorded_at
      ago
    - else
      no updates yet
  %p
    %strong Updates
    = @hunt.positions.count
  %h2 Map Details
  %p
    %strong Name
    = @hunt.map.name
  %p
    %strong Total Distance
    = human_distance @hunt.map.total_distance

.main.col12
  #hunt-display

.clear

:javascript
  
  var h = new HuntDisplay(#{@hunt.map.id}, 'hunt-display');
  h.showHunt(#{@hunt.id});
  