config/routes.rb
Huntapp::Application.routes.draw do
  resources :static_pages

  
  resources :maps do
    resources :waypoints, :only => [:new, :create]
    resources :hunts, :only => [:new, :index, :create]
  end
  
  resources :hunts, :only => [:show, :update, :destroy] do
    member do
      post 'sync'
    end
  end
  
  resources :positions, :only => [:show]
  
  resources :users, :only => [:new, :create]
  match "signup" => 'users#new', :as => :signup
  
  resource :user_sessions, :only => [:new, :create, :destroy]
  match "signin" => 'user_sessions#new', :as => :signin, :method => :get
  match "signout" => 'user_sessions#destroy', :as => :signout, :method => :destroy
  
  match "activity" => 'activity#index', :as => :activity
  match "live-hunts" => 'activity#public', :as => :live_hunts
  match "start-mapping" => 'maps#new'
  resources :waypoints, :except => [:new, :create]
  
  root :to => 'pages#home'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Track My Hunt</title>
  <%= stylesheet_link_tag :all %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=geometry&amp;sensor=false"></script>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body class="controller-<%= controller_name %> action-<%= action_name %>">
  <div id="application">
    <div id="header">
      <div class="limiter">
		<div id="h_search">
         <form><input name="search" id="search_input" /><input type="img" id="search_submit" /></form>
        </div>
	
        <h1><a href="/">Track My Hunt</a></h1>
        <ul id="secondary-navigation">
          <%- if current_user? -%>
          <li><%= link_to 'Activity', activity_path %></li>
          <li><%= link_to 'Sign Out', signout_path %></li>
          <%- else -%>
          <li><%= link_to 'Sign In', signin_path %></li>
          <li><%= link_to 'Sign Up', signup_path %></li>
          <%- end -%>
        </ul>
        <ul id="navigation">
          <li><a href="/">Home</a></li>
          <li><a href="/start-mapping">Start Mapping</a></li>
          <li><a href="/live-hunts">Live Hunts</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/links">Links</a></li>
        </ul>
      </div>
    </div>
    <div id="main">
      <div class="limiter">
        <%= yield %>
      </div>
    </div>
    <div id="footer">
        <div class="limiter">
		
         	<ul class="left footer_list footer_list_first">
	        	<li class="bold">NEED HELP?</li>
	            <li><a href="/ask_a_question">Ask a Question</a></li>
	            <li><a href="/site_feedback">Site Feedback</a></li>
	            <li><a href="/how_to_use">How to Use the App</a></li>
	        </ul>
	        <ul class="left footer_list">
	        	<li class="bold">OTHER STUFF</li>
	            <li><a href="#">Get the App</a></li>
				 <%- if current_user? -%>
					<li><%= link_to 'Sign Out', signout_path %></li>
	           	 <%- else -%>
			          <li><%= link_to 'Sign In', signin_path %></li>
			          <li><%= link_to 'Sign Up', signup_path %></li>
			     <%- end -%>
	            <li><a href="/how_it_works">How it Works</a></li>
	        </ul>
	        <ul class="left footer_list">
	        	<li class="bold">&copy; 2011 Outdoors Engineering</li>
	            <li><a href="/terms_of_use">Legal/Terms of Use</a></li>
	            <li><a href="/privacy_policy">Privacy Policy</a></li>

	        </ul>
        </div>
    </div>
  </div>

</body>
</html>